velocity: 4.0
vel_max_train: 4.0
acc_max_train: 4.0
wg: 0.15
ws: 10.0
wa: 2.0
wc: 1.5
wd: 75.0
detach_qvec: true
dataset_path: ../dataset
image_height: 96
image_width: 160
horizon_num: 5
vertical_num: 3
horizon_camera_fov: 90.0
vertical_camera_fov: 60.0
horizon_anchor_fov: 30.0
vertical_anchor_fov: 30.0
radio_range: 5.0
radio_num: 1
d0: 1.2
r: 0.6
vx_mean_unit: 0.4
vy_mean_unit: 0.0
vz_mean_unit: 0.0
vx_std_unit: 2.0
vy_std_unit: 0.45
vz_std_unit: 0.3
ax_mean_unit: 0.0
ay_mean_unit: 0.0
az_mean_unit: 0.0
ax_std_unit: 0.5
ay_std_unit: 0.5
az_std_unit: 0.3
goal_pitch_std: 10.0
goal_yaw_std: 20.0
map_expand_min:
- 0
- 0
- 0.2
map_expand_max:
- 0
- 0
- 6.0
pendulum_encoder:
  latent_dim: 8
gradient_decay: true
score_dyn_boost: 5.0
payload:
  cable_length: 0.8
  mass: 0.3
bubble:
  r_uav: 0.35
  r_load: 0.15
  r_safe: 0.08
