"""
Spherical Pendulum ODE Simulator for UAV-Payload Transportation.

Replaces random payload state sampling with physically consistent states
generated by integrating the spherical pendulum equations of motion under
random (but physically plausible) UAV acceleration inputs.

Equations of motion (spherical pendulum, pivot = UAV):
  In the non-inertial frame of the pivot:
    g_eff = [0, 0, -g] - a_UAV   (effective gravity)

  theta_ddot = phi_dot^2 * sin(theta)*cos(theta)
               + (1/L) * g_eff · e_theta
  phi_ddot   = (1/(L*sin(theta))) * g_eff · e_phi
               - 2 * theta_dot * phi_dot * cos(theta)/sin(theta)

  where:
    theta = polar angle from vertical (0 = straight down)
    phi   = azimuth angle
    e_theta = [cos(theta)*cos(phi), cos(theta)*sin(phi), sin(theta)]
    e_phi   = [-sin(phi), cos(phi), 0]
"""

import logging
import numpy as np
from scipy.integrate import solve_ivp
import os
import sys

logger = logging.getLogger(__name__)

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

G = 9.81  # m/s^2


def pendulum_ode(t, y, acc_func, L):
    """
    Spherical pendulum ODE with moving pivot — Cartesian internal representation.

    Uses Cartesian payload position (relative to pivot) internally to avoid
    the theta=0 singularity that caused runaway instability in the previous
    spherical-coordinate formulation.

    State y = [qx, qy, qz, dqx, dqy, dqz] — unit direction vector q = r/L
    and its time derivative dq.

    The constraint |q| = 1 is enforced via projection (Baumgarte stabilisation).

    Args:
        y: [qx, qy, qz, dqx, dqy, dqz]
        acc_func: callable t -> [ax, ay, az] (UAV acceleration in world frame)
        L: cable length (m)

    Returns:
        dy/dt
    """
    qx, qy, qz, dqx, dqy, dqz = y
    q = np.array([qx, qy, qz])
    dq = np.array([dqx, dqy, dqz])

    # Renormalize q to unit length (Baumgarte stabilisation)
    q_norm = np.linalg.norm(q)
    if q_norm < 1e-10:
        q = np.array([0.0, 0.0, -1.0])
        q_norm = 1.0
    q = q / q_norm

    ax, ay, az = acc_func(t)
    # Effective gravity in non-inertial pivot frame: g_eff = gravity - UAV_accel
    g_eff = np.array([-ax, -ay, -(G + az)])

    # Constrained acceleration: project out radial component
    # ddq = (g_eff - (g_eff · q) q - |dq|^2 q) / L
    # But since |q|=1: ddq = (g_eff - (g_eff · q) q) / L - (dq · dq) q
    # Plus Baumgarte correction: - 2*alpha*(dq · q)*q - alpha^2*(|q|^2 - 1)*q
    g_tangent = g_eff - np.dot(g_eff, q) * q
    centripetal = np.dot(dq, dq) * q

    # Baumgarte stabilisation coefficients
    alpha = 50.0
    constraint_vel = np.dot(dq, q)
    constraint_pos = q_norm - 1.0

    ddq = g_tangent / L - centripetal - 2 * alpha * constraint_vel * q - alpha**2 * constraint_pos * q

    return [dqx, dqy, dqz, ddq[0], ddq[1], ddq[2]]


def spherical_to_cartesian(theta, phi):
    """Convert spherical (theta, phi) to unit direction vector q.
    theta=0 → straight down q=[0,0,-1].
    """
    st, ct = np.sin(theta), np.cos(theta)
    sp, cp = np.cos(phi), np.sin(phi)  # Note: original convention
    # Payload position: r = L * [sin(theta)*cos(phi), sin(theta)*sin(phi), -cos(theta)]
    return np.array([st * cp, st * sp, -ct])


def cartesian_to_spherical(q):
    """Convert unit direction vector q back to (theta, phi).
    theta = angle from downward vertical [0, pi].
    """
    q = q / (np.linalg.norm(q) + 1e-15)
    # theta = angle from -z axis
    theta = np.arccos(np.clip(-q[2], -1.0, 1.0))
    phi = np.arctan2(q[1], q[0])
    return theta, phi


def state_spherical_to_cartesian(y_spherical):
    """Convert [theta, phi, dtheta, dphi] → [qx, qy, qz, dqx, dqy, dqz]."""
    theta, phi, dtheta, dphi = y_spherical
    q = spherical_to_cartesian(theta, phi)

    # dq/dt = d/dt [sin(theta)*cos(phi), sin(theta)*sin(phi), -cos(theta)]
    st, ct = np.sin(theta), np.cos(theta)
    sp, cp = np.sin(phi), np.cos(phi)
    dqx = ct * cp * dtheta - st * sp * dphi
    dqy = ct * sp * dtheta + st * cp * dphi
    dqz = st * dtheta
    return [q[0], q[1], q[2], dqx, dqy, dqz]


def state_cartesian_to_spherical(y_cartesian):
    """Convert [qx, qy, qz, dqx, dqy, dqz] → [theta, phi, dtheta, dphi]."""
    qx, qy, qz, dqx, dqy, dqz = y_cartesian
    q = np.array([qx, qy, qz])
    q = q / (np.linalg.norm(q) + 1e-15)
    theta, phi = cartesian_to_spherical(q)

    st = np.sin(theta)
    ct = np.cos(theta)
    sp = np.sin(phi)
    cp = np.cos(phi)

    # Invert the Jacobian to get dtheta, dphi from dqx, dqy, dqz
    # dq = J * [dtheta, dphi]^T  where J is 3x2
    # Use pseudoinverse: [dtheta, dphi] = J^+ * dq
    if abs(st) > 1e-8:
        # From dqz = sin(theta) * dtheta
        dtheta = dqz / (st + 1e-15) if abs(st) > 1e-8 else 0.0
        # From dqx = cos(theta)*cos(phi)*dtheta - sin(theta)*sin(phi)*dphi
        dphi = (dqy - ct * sp * dtheta) / (st * cp + 1e-15) if abs(st * cp) > 1e-8 else \
               -(dqx - ct * cp * dtheta) / (st * sp + 1e-15) if abs(st * sp) > 1e-8 else 0.0
    else:
        dtheta = np.sqrt(dqx**2 + dqy**2)
        dphi = 0.0

    return [theta, phi, dtheta, dphi]


def simulate_pendulum(y0, L, T, acc_func, dt=0.05):
    """
    Integrate pendulum ODE over time T.

    Args:
        y0: initial state [theta0, phi0, dtheta0, dphi0] (spherical coords)
        L:  cable length (m)
        T:  total simulation time (s)
        acc_func: callable(t) -> [ax, ay, az]
        dt: output time step (s)

    Returns:
        t_out: (N,) time array
        y_out: (N, 4) state array [theta, phi, dtheta, dphi]
    """
    # Convert spherical initial state to Cartesian for integration
    y0_cart = state_spherical_to_cartesian(y0)

    t_eval = np.arange(0, T, dt)
    t_eval = np.clip(t_eval, 0, T * (1 - 1e-9))  # ensure within t_span
    sol = solve_ivp(
        fun=lambda t, y: pendulum_ode(t, y, acc_func, L),
        t_span=(0, T),
        y0=y0_cart,
        t_eval=t_eval,
        method='RK45',
        rtol=1e-6,
        atol=1e-8,
        max_step=dt / 2.0,
    )

    # Convert back to spherical for output
    y_cart = sol.y.T  # (N, 6)
    y_sph = np.zeros((len(y_cart), 4))
    for i in range(len(y_cart)):
        y_sph[i] = state_cartesian_to_spherical(y_cart[i])

    return sol.t, y_sph  # (N,), (N, 4)


# ---------------------------------------------------------------------------
# Random acceleration generator (sinusoidal + Gaussian noise, bandwidth < 2 Hz)
# ---------------------------------------------------------------------------

def make_random_acc_func(vel_max=4.0, acc_max=4.0, T=20.0, seed=None):
    """
    Generate a smoothly varying, physically plausible UAV acceleration profile.
    Uses a sum of low-frequency sinusoids + low-pass filtered noise.
    """
    rng = np.random.default_rng(seed)
    n_freq = 5
    amps = rng.uniform(0, acc_max / n_freq, size=(3, n_freq))
    freqs = rng.uniform(0.1, 1.5, size=(3, n_freq))       # Hz, up to 1.5 Hz
    phases = rng.uniform(0, 2 * np.pi, size=(3, n_freq))

    def acc_func(t):
        a = np.zeros(3)
        for k in range(n_freq):
            a += amps[:, k] * np.sin(2 * np.pi * freqs[:, k] * t + phases[:, k])
        return np.clip(a, -acc_max, acc_max)

    return acc_func


# ---------------------------------------------------------------------------
# Dataset state generator
# ---------------------------------------------------------------------------

def generate_payload_state_library(
    n_samples: int = 200_000,
    L_fixed: float = 0.8,
    m_fixed: float = 0.3,
    T_sim: float = 20.0,
    sample_interval: float = 0.1,
    acc_max: float = 4.0,
    seed: int = 42,
) -> np.ndarray:
    """
    Generate a library of physically realistic payload states by simulating
    many spherical pendulums under random UAV acceleration profiles.

    Uses fixed cable length and mass — these are unknown at deployment,
    so the network should not depend on them.

    Returns:
        states: (n_samples, 6) array of [theta, phi, dtheta, dphi, L, m]
    """
    rng = np.random.default_rng(seed)
    states = []
    fail_count = 0

    samples_per_run = int(T_sim / sample_interval)
    n_runs = int(np.ceil(n_samples / samples_per_run)) + 1

    for run_idx in range(n_runs):
        if len(states) >= n_samples:
            break

        L = L_fixed
        m = m_fixed

        # Random initial condition (small initial swing)
        theta0 = rng.uniform(0.0, 0.3)     # up to ~17 deg
        phi0   = rng.uniform(0, 2 * np.pi)
        dtheta0 = rng.uniform(-0.5, 0.5)
        dphi0   = rng.uniform(-0.5, 0.5)

        acc_func = make_random_acc_func(acc_max=acc_max, T=T_sim,
                                        seed=rng.integers(0, 2**31))

        try:
            t_out, y_out = simulate_pendulum(
                y0=[theta0, phi0, dtheta0, dphi0],
                L=L,
                T=T_sim,
                acc_func=acc_func,
                dt=sample_interval,
            )
        except Exception as e:
            fail_count += 1
            if fail_count <= 5:
                logger.warning("ODE integration failed (run %d): %s", run_idx, e)
            continue

        for i in range(len(t_out)):
            theta, phi, dtheta, dphi = y_out[i]
            # Normalize: theta in [0, pi], phi in [-pi, pi]
            theta = abs(theta)  # theta is a polar angle, always >= 0
            phi = (phi + np.pi) % (2 * np.pi) - np.pi  # wrap to [-pi, pi]
            # Filter physically unrealistic states
            if theta > np.pi * 0.9 or np.abs(dtheta) > 5.0 or np.abs(dphi) > 10.0:
                continue
            states.append([theta, phi, dtheta, dphi, L, m])
            if len(states) >= n_samples:
                break

    if fail_count > 0:
        logger.warning("Total ODE integration failures: %d / %d runs", fail_count, n_runs)
    states = np.array(states[:n_samples], dtype=np.float32)
    return states


def save_payload_state_library(output_path: str, n_samples: int = 200_000, seed: int = 42):
    """
    Generate and save payload state library to a .npy file.
    Run once before training; loaded by YOPODataset during initialization.
    """
    print(f"Generating {n_samples} physically consistent payload states...")
    states = generate_payload_state_library(n_samples=n_samples, seed=seed)
    np.save(output_path, states)
    print(f"Saved payload state library to {output_path}")
    print(f"  theta range:  [{states[:, 0].min():.3f}, {states[:, 0].max():.3f}] rad")
    print(f"  phi range:    [{states[:, 1].min():.3f}, {states[:, 1].max():.3f}] rad")
    print(f"  dtheta range: [{states[:, 2].min():.3f}, {states[:, 2].max():.3f}] rad/s")
    print(f"  dphi range:   [{states[:, 3].min():.3f}, {states[:, 3].max():.3f}] rad/s")
    print(f"  L range:      [{states[:, 4].min():.3f}, {states[:, 4].max():.3f}] m")
    print(f"  m range:      [{states[:, 5].min():.3f}, {states[:, 5].max():.3f}] kg")
    return states


# ---------------------------------------------------------------------------
# Validation: correlate DynamicsLoss proxy with true ODE swing
# ---------------------------------------------------------------------------

def validate_dynamics_proxy(
    n_trajs: int = 500,
    L_range: tuple = (0.3, 1.5),
    acc_max: float = 6.0,
    T_traj: float = 2.0,
    dt: float = 0.05,
    seed: int = 0,
) -> dict:
    """
    For each test trajectory:
    1. Generate a polynomial trajectory (constant acceleration segment)
    2. Compute DynamicsLoss proxy: target_theta from quasi-static model
    3. Simulate actual pendulum ODE along the trajectory
    4. Compute correlation between proxy and actual peak swing

    Returns a dict with proxy values, true peak swings, and correlation stats.
    """
    rng = np.random.default_rng(seed)

    proxy_values = []
    true_peak_swings = []
    true_mean_swings = []
    fail_count = 0

    for traj_idx in range(n_trajs):
        L = rng.uniform(*L_range)

        # Random constant acceleration (simplified trajectory segment)
        ax = rng.uniform(-acc_max * 0.5, acc_max * 0.5)
        ay = rng.uniform(-acc_max * 0.5, acc_max * 0.5)
        az = rng.uniform(-acc_max * 0.3, acc_max * 0.3)

        def acc_func(t, _ax=ax, _ay=ay, _az=az):
            return np.array([_ax, _ay, _az])

        # Initial payload state (slightly disturbed)
        theta0 = rng.uniform(0.0, 0.2)
        phi0   = rng.uniform(0, 2 * np.pi)
        dtheta0 = rng.uniform(-0.3, 0.3)
        dphi0   = rng.uniform(-0.3, 0.3)

        try:
            t_out, y_out = simulate_pendulum(
                y0=[theta0, phi0, dtheta0, dphi0],
                L=L, T=T_traj,
                acc_func=acc_func,
                dt=dt,
            )
        except Exception as e:
            fail_count += 1
            if fail_count <= 5:
                logger.warning("Validation ODE failed (traj %d): %s", traj_idx, e)
            continue

        true_thetas = y_out[:, 0]
        true_peak = float(np.max(np.abs(true_thetas)))
        true_mean = float(np.mean(np.abs(true_thetas)))

        # DynamicsLoss proxy (quasi-static equilibrium angle)
        acc_xy_norm = np.sqrt(ax**2 + ay**2)
        target_theta_proxy = np.arctan(acc_xy_norm / max(az + G, 1e-3))
        total_swing = target_theta_proxy + 0.2 * abs(theta0 - target_theta_proxy)
        length_penalty = 1.0 / max(L, 0.1)
        proxy_val = total_swing * length_penalty

        proxy_values.append(proxy_val)
        true_peak_swings.append(true_peak)
        true_mean_swings.append(true_mean)

    proxy_arr = np.array(proxy_values)
    peak_arr  = np.array(true_peak_swings)
    mean_arr  = np.array(true_mean_swings)

    from scipy.stats import pearsonr, spearmanr
    r_peak, p_peak   = pearsonr(proxy_arr, peak_arr)
    rho_peak, _      = spearmanr(proxy_arr, peak_arr)
    r_mean, p_mean   = pearsonr(proxy_arr, mean_arr)

    results = {
        "n_trajs": len(proxy_arr),
        "pearson_r_peak": r_peak,
        "pearson_p_peak": p_peak,
        "spearman_rho_peak": rho_peak,
        "pearson_r_mean": r_mean,
        "proxy_values": proxy_arr,
        "true_peak_swings_rad": peak_arr,
        "true_mean_swings_rad": mean_arr,
    }
    return results


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=["generate", "validate", "both"], default="both")
    parser.add_argument("--n_samples", type=int, default=200_000)
    parser.add_argument("--output", type=str, default="../dataset/payload_state_library.npy")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    if args.mode in ("generate", "both"):
        save_payload_state_library(args.output, args.n_samples, args.seed)

    if args.mode in ("validate", "both"):
        print("\nValidating DynamicsLoss proxy vs. ODE simulation...")
        results = validate_dynamics_proxy(n_trajs=1000, seed=args.seed)
        print(f"  Trajectories evaluated: {results['n_trajs']}")
        print(f"  Pearson r (proxy vs peak swing):  {results['pearson_r_peak']:.3f}  (p={results['pearson_p_peak']:.2e})")
        print(f"  Spearman ρ (proxy vs peak swing): {results['spearman_rho_peak']:.3f}")
        print(f"  Pearson r (proxy vs mean swing):  {results['pearson_r_mean']:.3f}")
        print(f"\n  Mean true peak swing: {results['true_peak_swings_rad'].mean():.3f} rad "
              f"({np.degrees(results['true_peak_swings_rad'].mean()):.1f} deg)")
        print(f"  Mean proxy value:     {results['proxy_values'].mean():.3f}")
